apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnaloud-backend
  namespace: learnaloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnaloud-backend
  template:
    metadata:
      labels:
        app: learnaloud-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/psantanusaha/learnaloud-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: learnaloud-secrets
        env:
        - name: FLASK_ENV
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "*"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
